import { Request, Response } from "express";
import { Client } from "pg";
import { randomInt } from "crypto";
import { verifyRingSignature } from "./ringSignature";

// Initialize Postgres client
const pgClient = new Client({ connectionString: process.env.DATABASE_URL });
pgClient.connect().catch((err) => {
  console.error("[POST CONTROLLER] Failed to connect to pg database:", err);
});

// Timing Obfuscation Helper to prevent temporal correlation attacks
async function injectTimingObfuscationDelay(): Promise<void> {
  if (process.env.NODE_ENV === "test") {
    return;
  }
  const delay = randomInt(50, 1500); // 50ms to 1500ms delay
  return new Promise((resolve) => setTimeout(resolve, delay));
}

/**
 * Endpoint to publish an anonymous post using Ring Signatures.
 */
export const createPost = async (req: Request, res: Response): Promise<void> => {
  if (req.body.geoHash) {
    res.status(400).json({ error: "Legacy parameter geoHash is not supported. Use macroRegionCellId." });
    return;
  }

  const { ipfsHash, macroRegionCellId, ringSignature, messagePayload } = req.body;

  try {
    if (!ipfsHash || !macroRegionCellId || !ringSignature || !messagePayload) {
      res.status(400).json({ error: "Missing required post parameters: ipfsHash, macroRegionCellId, ringSignature, or messagePayload." });
      return;
    }

    if (
      typeof ringSignature !== "object" ||
      !ringSignature.c0 ||
      !Array.isArray(ringSignature.s) ||
      !ringSignature.keyImage
    ) {
      res.status(400).json({ error: "Invalid ringSignature structure. Expected { c0, s: string[], keyImage }." });
      return;
    }

    // 1. Fetch active ring of public keys matching that specific cell ID from PostgreSQL
    const result = await pgClient.query("SELECT public_key FROM user_identities WHERE assigned_cell_id = $1", [macroRegionCellId]);
    const ring = result.rows.map((row) => row.public_key);

    if (ring.length < 2) {
      res.status(401).json({ error: "Ring signature verification requires at least 2 registered public keys in the ring." });
      return;
    }

    // 2. Verify that the ringSignature was generated by a valid member of the ring
    const isValid = verifyRingSignature(messagePayload, ring, ringSignature);
    if (!isValid) {
      res.status(401).json({ error: "Invalid ring signature. Authenticity verification failed." });
      return;
    }

    // 3. Decouple database commit from packet arrival time via timing obfuscation guardrail
    await injectTimingObfuscationDelay();

    // 4. Write post metadata to relational schema
    // CRITICAL: Do NOT store ownerIdentityHash, user_id, or any other tracking parameters.
    await pgClient.query(
      "INSERT INTO decentralized_posts (ipfs_hash, macro_region_cell_id) VALUES ($1, $2)",
      [ipfsHash, macroRegionCellId]
    );

    res.status(200).json({
      success: true,
      message: "Post verified and queued for publishing anonymously."
    });
  } catch (error) {
    console.error("[POST CONTROLLER ERROR] Failed to publish anonymous post:", error);
    res.status(500).json({ error: "Internal server error." });
  }
};

